### ISSUE TITLE
Issue with get-ncdc_station_data

### ISSUE THREAD

**Issue by pssguy** [rich-iannone/stationaRy#3] opened 2015-06-18 17:40 UTC
From the list of stations, I wish to obtain detailed data for the LAKEFRONT AIRPORT station
USAF 722315 WBAN 53917 in Louisiana

```
station_data <- get_ncdc_station_data(station_id = "722315-53917",
                                  startyear = 2014,
                                  endyear = 2015)
```

Error in if (tz != "UTC") { : missing value where TRUE/FALSE needed

**Comment by rich-iannone** [comment] 2015-06-18 19:57
The issue is that that location cannot be resolved with a time zone offset. It has lat/lon data but is failing when determining which polygon the point is in. I'm running a script to determine which stations fail and I'll augment the package with a data file containing to offsets for each site. Eventually, I could drop the use of the shapefile in the package altogether.

In the meantime, I will include an option to have the user manually specify the time zone offset from UTC+0.

**Comment by pssguy** [comment] 2015-06-18 22:23
Thanks for following this up

In the interim, is there a way to stop processing if the function fails? I am working on a shiny/leaflet app where station locations are indicated by circles. The user can click on them which sets off within an observe function

```
     met_data <- get_ncdc_station_data()  
```

If there is no data, I get a

```
Warning: Unhandled error in observer: argument is of length zero
```

However, although I do a test

```
if (length(met_data)==0) return()
```

the app crashes

**Comment by rich-iannone** [comment] 2015-06-20 20:08
@pssguy I put in a workaround to help out a bit. The `get_ncdc_station_data` function now has a `local_tz` argument. Setting to `FALSE` means no tz correction and it so it won't use the `get_tz_offset` function, which needs to be more rigorously tested (and currently fails on your station and, from my tests, quite a few others). Let me know if that helps for now.

**Comment by pssguy** [comment] 2015-06-20 20:51
Does 
    devtools::install_github('rich-iannone/stationaRy')
get me to the updated version?

Here is what I get for the LAKEFRONT AIRPORT station in Louisiana

```
get_ncdc_station_data(station_id = "722315-53917",
                        startyear = 2014,
                        endyear = 2015,
                        local_tz = FALSE)

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2014/722315-53917-2014.gz'
downloaded 664 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2015/722315-53917-2015.gz'
downloaded 322 KB
```

The files appear to be downloading but then I get

```
Error in get_ncdc_station_data(station_id = "722315-53917", startyear = 2014,  : 
  object 'tz_offset' not found
```

The same happens if I manually input an offset i.e. local_tz = -5

Alternatively

```
       get_ncdc_station_data(station_id = "722315-53917",
                                                          startyear = 2014,
                                                           endyear = 2015)
    Error in if (tz != "UTC") { : missing value where TRUE/FALSE needed
```

No downloading at all . ditto, as expected, setting local-tz = TRUE

**Comment by rich-iannone** [comment] 2015-06-20 21:09
@pssguy yes, the `devtools` install method will get you the latest package from GitHub with the workaround included. Give that a try and run again. If the same problems occur, I'll address them.

**Comment by pssguy** [comment] 2015-06-20 21:29
The above was after I installed the new version and restarted R. Can you confirm?

**Comment by rich-iannone** [comment] 2015-06-20 22:51
@pssguy It works when using `local_tz = FALSE`. Here's the console output.

```
> get_ncdc_station_data(station_id = "722315-53917",
+                       startyear = 2014,
+                       endyear = 2015,
+                       local_tz = FALSE)
trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2014/722315-53917-2014.gz'
ftp data connection made, file length 680021 bytes
==================================================
downloaded 664 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2015/722315-53917-2015.gz'
ftp data connection made, file length 329777 bytes
==================================================
downloaded 322 KB

Source: local data frame [17,617 x 18]

     usaf  wban year month day hour minute    lat     lon elev  wd  ws ceil_hgt temp dew_point atmos_pres   rh
1  722315 53917 2014     1   1    0     53 30.049 -90.029    3  60 4.6    22000  8.3       5.0     1027.8 79.7
2  722315 53917 2014     1   1    1     53 30.049 -90.029    3  50 5.1     3048  7.8       5.0     1027.8 82.5
3  722315 53917 2014     1   1    2     53 30.049 -90.029    3  70 4.1     3353  8.3       5.6     1028.1 83.1
4  722315 53917 2014     1   1    3     53 30.049 -90.029    3  80 4.6     2591  7.8       5.6     1027.8 86.0
5  722315 53917 2014     1   1    4     53 30.049 -90.029    3  60 4.6     3353  7.8       5.6     1027.4 86.0
6  722315 53917 2014     1   1    5     53 30.049 -90.029    3 100 5.7     3353  7.8       6.1     1026.0 89.0
7  722315 53917 2014     1   1    5     59 30.049 -90.029    3  NA  NA       NA   NA        NA         NA   NA
8  722315 53917 2014     1   1    5     59 30.049 -90.029    3  NA  NA       NA   NA        NA         NA   NA
9  722315 53917 2014     1   1    6     53 30.049 -90.029    3 100 4.1     3658  7.8       6.1     1025.8 89.0
10 722315 53917 2014     1   1    7     53 30.049 -90.029    3 110 4.6     2743  8.9       7.2     1024.9 89.1
..    ...   ...  ...   ... ...  ...    ...    ...     ...  ... ... ...      ...  ...       ...        ...  ...
Variables not shown: time (time)
```

**Comment by pssguy** [comment] 2015-06-20 23:08
That's weird. I'm still getting the 

```
Error in get_ncdc_station_data(station_id = "722315-53917", startyear = 2014,  : 
  object 'tz_offset' not found
```

You only have the master branch, right?

**Comment by rich-iannone** [comment] 2015-06-20 23:12
@pssguy Yes, there's just the master branch and everything has been pushed. Checked the code in the function and it's also even with what I have. Perhaps remove the package and then do a fresh install from GitHub.

**Comment by pssguy** [comment] 2015-06-21 04:01
Thanks for suggestion. Still no change. here is my sessionInfo()

R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stationaRy_0.2

loaded via a namespace (and not attached):
 [1] readr_0.1.1     magrittr_1.5    plyr_1.8.3      proj4_1.0-8     tools_3.2.0     sp_1.1-1  
 [7] memoise_0.2.1   Rcpp_0.11.6     downloader_0.3  lubridate_1.3.3 stringi_0.4-1   grid_3.2.0  
[13] stringr_1.0.0   digest_0.6.8    lattice_0.20-31

**Comment by rich-iannone** [comment] 2015-06-21 18:16
Okay, this is very strange indeed. Just as a sanity check, could you echo the `get_ncdc_station_data` function in the console and make sure it matches the function in the repo? It should contain two `if (local_tz == TRUE){ ... }` blocks.

**Comment by pssguy** [comment] 2015-06-21 22:07
The 2 blocks look like this

    if (local_tz == TRUE) {
    tz_offset <- get_tz_offset(target_station$LON[1], target_station$LAT[1])
    if (tz_offset > 0) 
      startyear <- startyear - 1
    if (tz_offset < 0) 
      endyear <- endyear + 1
  }

**Comment by pssguy** [comment] 2015-06-21 22:08
The 2 blocks look like this

```
if (local_tz == TRUE) {
tz_offset <- get_tz_offset(target_station$LON[1], target_station$LAT[1])
if (tz_offset > 0) 
  startyear <- startyear - 1
if (tz_offset < 0) 
  endyear <- endyear + 1
```

  }

and

```
if (local_tz == TRUE) {
if (tz_offset > 0) 
  startyear <- startyear + 1
if (tz_offset < 0) 
  endyear <- endyear - 1
```

  }

The only obvious difference is that the if statements are spread over 2 lines locally. Do they need  curly braces in this case?

**Comment by rich-iannone** [comment] 2015-06-22 00:03
Still not really sure why this wouldn't work for you yet it does for me. At any rate, I'm collecting tz data from GeoNames for all the sites, so, the tz/shapefile method will no longer be required (and these conditional statements can be removed, since there will be tz offset values). The data collection is a bit slow because of the rate limit imposed by GeoNames (2000 API calls/hour).

Still, I hope to get this data into the package ASAP and, in the process, thin the size of the package by eliminating the large shapefile.

**Comment by pssguy** [comment] 2015-06-22 18:16
Guess just one of those mysteries not worth pursuing
Thanks for investigating and enhancing package. Do you have a time-frame for including the tz data?

**Comment by rich-iannone** [comment] 2015-06-22 19:27
I'm shooting for some time late tonight.

**Comment by rich-iannone** [comment] 2015-06-23 06:11
Okay, the package has been revised. A lot. Get the GitHub version with `devtools::install_github` and try this:

```
get_isd_station_data(station_id = "722315-53917",
                                startyear = 2014,
                                endyear = 2015)
```

Let me know if this is not working out on your end.

**Comment by pssguy** [comment] 2015-06-23 17:37
That's quite the revamp. Congrats
Looks good  and have also tried one or two other sites where 2014/15 data are available
I see that it also tries to download 2016 data

```
trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2016/722315-53917-2016.gz'
```

which obviously currently has none and adds to time of response

Is this done to cater for time differences at the turn of a year?
If so, is there anyway to suppress unless the current date is apprpriate? I am working on an app where the user clicks on a specific location clicked on a leaflet map to obtain the relevant station data and anything that can speed the result would be helpful

**Comment by rich-iannone** [comment] 2015-06-25 22:14
@pssguy after a few more revisions, everything seems to work well! There won't be attempts to download files which are beyond the current year. Also, a proper subset based on the time-corrected POSIXct times is now done so just records for the years requested are returned. Please test again and ensure that everything works on your end.

**Closed as completed by rich-iannone** 2015-06-25 22:14 UTC

**Comment by pssguy** [comment] 2015-06-25 22:56
Looks good. Thanks again
